### PR TITLE
Initialize rabbit for step rake task.

### LINKED ISSUE #592: workflow:step rake task errors on last line
This line throws an error if you try to run the rake task, e.g. in prod:

```
$ RAILS_ENV=production bin/rake workflow:step[druid:bc123df4567,preservationIngestWF,transfer-object,1,waiting]
Setting transfer-object to waiting
rake aborted!
NoMethodError: undefined method `topic' for nil:NilClass
/opt/app/workflow/workflow-server-rails/releases/20220808213318/app/services/send_rabbitmq_message.rb:18:in `publish'
/opt/app/workflow/workflow-server-rails/releases/20220808213318/app/services/send_rabbitmq_message.rb:7:in `publish'
/opt/app/workflow/workflow-server-rails/releases/20220808213318/app/services/send_update_message.rb:8:in `publish'
/opt/app/workflow/workflow-server-rails/releases/20220808213318/lib/tasks/workflow.rake:21:in `block (2 levels) in <main>'
Tasks: TOP => workflow:step
(See full trace by running task with --trace)
```

https://github.com/sul-dlss/workflow-server-rails/blob/d56e813e7847e0d8e1331a94b73047c147603edc/lib/tasks/workflow.rake#L4-L22

https://github.com/sul-dlss/workflow-server-rails/blob/d56e813e7847e0d8e1331a94b73047c147603edc/app/services/send_rabbitmq_message.rb#L5-L20

The workflow step is reset, but the RabbitMQ, message isn't sent.  From glancing at the rake task and the code being called by the line throwing the error, it seems like maybe `$rabbitmq_channel` isn't being set, based on the initializer that sets it specifically not running if passenger isn't where the invocation ultimately comes from:

https://github.com/sul-dlss/workflow-server-rails/blob/2a2e5b5c0d4975684f000acd3ad93141d9b87cdd/config/initializers/bunny_connection_after_fork.rb#L9-L22

### PR DESCRIPTION
**Pull request by justinlittman**
closes  #592

## Why was this change made? 🤔
Rake task not working correctly.

## How was this change tested? 🤨

QA

⚡ ⚠ If this change affects consumers, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** that exercise this service and/or test in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

**Comment by justinlittman** [comment]
```
$ RAILS_ENV=production bundle exec rake workflow:step['druid:bb573tm8486','accessionWF','technical-metadata','3','waiting']
Setting technical-metadata to waiting
```

**Comment by justinlittman** [comment]
Dear reviewer:

I don't think this refactor merits a test, but I welcome your feedback.

**Review by jmartin-sul — APPROVED** [review]

**Comment by jmartin-sul** [comment]
> Dear reviewer:
> 
> I don't think this refactor merits a test, but I welcome your feedback.

agreed.  seems a little difficult to unit test in a meaningful way, and integration tests should tell us whether we broke anything (plus, it's a pretty short and reviewable refactor).

**Comment by jmartin-sul** [comment]
also i really like `RabbitFactory` as a class name, for some reason 🐇 🐇

**Pull request merged**
