### PR TITLE
Changes handling of stuck workflow steps.

### PR DESCRIPTION
**Pull request by justinlittman**
Add monitoring for stuck workflow steps. Disables sweeping of stuck workflow steps.

## Why was this change made?
Our current sweeper is requeueing long-running jobs.

See https://github.com/sul-dlss/common-accessioning/issues/505

## Was the documentation (API, README, DevOpsDocs, wiki, consul, etc.) updated?
No.

### CODE REVIEW

**Comment by ndushay** [comment]
Why is this on hold?

**Comment by justinlittman** [comment]
Waiting for Honeybadger to be back to its old self.

**Comment by jcoyne** [comment]
I propose we hold this until https://github.com/sul-dlss/workflow-server-rails/pull/280 is in prod.

**Comment by mjgiarlo** [comment]
@jcoyne @justinlittman #280 is now in prod.

**Comment by ndushay** [comment]
is there any reason this is in "review/QA" column instead of closed?  If yes, what needs to be done for it to be closed?

**Comment by mjgiarlo** [comment]
@ndushay I see closed as the pipeline near the top of this page. maybe it's a linked issue that remains open? @justinlittman

**Pull request merged**
