### PR TITLE
add shell definitions for new OCR and caption workflows

### LINKED ISSUE #742: Create new ocr and caption workflow defintions
Two new workflows:
- ocr
- caption

Each starts with three steps:
- start
- do thing
- end

Robots to follow, will be no-op for now.  See sul-dlss/common-accessioning#1167

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made? 🤔

Fixes #742 ... add new workflow definitions for OCR and captioning

NOTE: it is quite possible that we will need additional steps as we progress through the workcycle, but it is straightforward to add these later, so I'd suggest we get started with these.

## How was this change tested? 🤨

Localhost using dor-workflow-client ensuring new workflow definitions are created and progress as expected from one step to the next when completing the previous step

### CODE REVIEW

**Comment by justinlittman** [comment]
Can you use "ocrWF" and "captionWF" to be consistent with existing naming conventions?

**Comment by peetucket** [comment]
> Can you use "ocrWF" and "captionWF" to be consistent with existing naming conventions?

I am agnostic, this was discussed in a thread in Slack: https://stanfordlib.slack.com/archives/C06EVDJV45N/p1713218802781899

Opinion seems split.  I can definitely see the argument for consistency.

**Comment by peetucket** [comment]
Added `WF` suffix for consistency.

**Review by edsu — APPROVED** [review]
🚀

**Pull request merged**
