### PR TITLE
Add github version badge

### PR DESCRIPTION
**Pull request by tallenaz**

### CODE REVIEW

**Comment by jcoyne** [comment]
I'm not sure I understand the point of this. Isn't the version just the deployed hash code?

**Comment by tallenaz** [comment]
This is to fulfill a DevOpsDocs requirement to set a badge for the application version where that means a release number. For example, the preservation_catalog badge is at 1.9.0

**Comment by jcoyne** [comment]
@tallenaz We need to rethink that requirement.  We should look at the the git version as it's the most clear and correct indicator for what is actually released/deployed. I suspect this requirement was written before we had honeybadger telling the #deploy channel what is released and when.  How should I propose a change to that procedure?  Is a PR on DevOpsDocs appropriate?

**Comment by tallenaz** [comment]
@jcoyne I think a DevOpsDocs PR should be part of the process, maybe with the requirement of a 3rd party review if we think more than the two of us should be involved in the rethinking. For myself, it doesn't seem too controversial, but there may be other opinions, etc.

**Comment by jcoyne** [comment]
Ref: https://github.com/sul-dlss/DevOpsDocs/pull/251

**Comment by ndushay** [comment]
can this be closed now, and the branch deleted?

**Comment by tallenaz** [comment]
Sure, thanks for the bump.

**Pull request closed without merging**
